#!/usr/bin/env python3
"""Regenerate sitemap.xml from the pages that exist.

    python3 scripts/build_sitemap.py

The list is derived rather than typed: every folder holding an index.html is a
page, plus the front page itself. Add a page and it appears here; nothing to
remember. "Data Viz" is left out on purpose -- those documents are diagrams,
only ever embedded, and on their own in a search result they are a chart with
no explanation around it. robots.txt disallows them for the same reason.

Priorities are a hint at relative importance within the site, nothing more;
search engines are free to ignore them, and mostly do.
"""

import os
import sys
from datetime import date

BASE = "https://algebraicsystemsbiology.github.io"

# Anything not named here gets the default. Order is the order they are written.
PRIORITY = {
    "/": "1.0",
    "/research/": "0.9",
    "/people/": "0.9",
    "/publications/": "0.8",
    "/engage/": "0.7",
    "/privacy/": "0.3",
}
DEFAULT_PRIORITY = "0.5"

SKIP = {".git", ".github", "node_modules", "_site", "pdf", "scripts",
        "assets", "images", "data", "partials", "documentation", "Data Viz"}


def urls(root="."):
    found = []
    if os.path.exists(os.path.join(root, "index.html")):
        found.append("/")
    for name in sorted(os.listdir(root)):
        if name in SKIP or name.startswith("."):
            continue
        if os.path.isdir(os.path.join(root, name)) and \
           os.path.exists(os.path.join(root, name, "index.html")):
            found.append(f"/{name}/")
    # Known pages first, in the order given above; anything new after them.
    ranked = [u for u in PRIORITY if u in found]
    ranked += [u for u in found if u not in PRIORITY]
    return ranked


def build(root="."):
    today = date.today().isoformat()
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           "<!-- Generated by scripts/build_sitemap.py. A double hyphen is illegal\n       inside an XML comment, which is why this one reads oddly. -->",
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc in urls(root):
        out += ["  <url>",
                f"    <loc>{BASE}{loc}</loc>",
                f"    <lastmod>{today}</lastmod>",
                f"    <priority>{PRIORITY.get(loc, DEFAULT_PRIORITY)}</priority>",
                "  </url>"]
    out.append("</urlset>")
    return "\n".join(out) + "\n"


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    path = os.path.join(root, "sitemap.xml")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(build(root))
    listed = urls(root)
    print(f"wrote {path}: {len(listed)} urls")
    for u in listed:
        print(f"  {BASE}{u}")


if __name__ == "__main__":
    sys.exit(main())
